name: CD

on:
  push:
    branches:
      - main

jobs:

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: india-devops-platform:${{ github.sha }}

      - name: Deployment Summary
        run: |
          echo "CD pipeline completed"
          echo "Docker image built successfully"
          echo "Image tag: india-devops-platform:${{ github.sha }}"

