name: CD

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy Docker with Terraform
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Check Docker
        run: |
          docker version
          docker info


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init


      - name: Terraform Validate
        working-directory: terraform
        run: |
          terraform validate


      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan


      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve


      - name: Verify Docker Container
        run: |
          docker ps


      - name: Test Application
        run: |
          curl --fail http://localhost:5000/health
